#!/command/with-contenv bash

# -------------------------------------------------
# Container Core Functions Script
# -------------------------------------------------
# This script defines core functions for container initialization,
# service management, and utility operations.

# -------------------------------
# Import Defaults
# -------------------------------
# Load default container configuration variables.
source /src/config/defaults/00-container

# -------------------------------
# Color Configuration
# -------------------------------
# Define background colors for terminal outputs.
bdg="\e[42m"       # Dark Green
bdb="\e[44m"       # Dark Blue
bdm="\e[45m"       # Dark Magenta
bdgy="\e[100m"     # Dark Gray
blr="\e[101m"      # Light Red
boff="\e[49m"      # Reset Background Color

# -------------------------------
# Initialization Checks
# -------------------------------
# Check if the container initialization scripts have completed.
check_container_initialized() {
    print_debug "Checking if container initialization scripts have completed"

    # Disable output to avoid cluttering logs.
    output_off

    # Loop until the initialization flag file is present.
    while [ ! -f /tmp/.container/99-container-init ]; do
        print_debug "Container initialization scripts not yet completed, retrying..."
        sleep 1
    done

    # Re-enable output after initialization is confirmed.
    output_on
}

# Check if a specific service within the container has been initialized.
check_service_initialized() {
    print_debug "Checking if service has been initialized"

    # Disable output to avoid cluttering logs.
    output_off

    # Determine the service suffix and bypass flag based on input arguments.
    if [ "$1" = "init" ]; then
        service_suffix="-init"
        csi_bypass=FALSE
    else
        service="$1"
        csi_bypass=TRUE
    fi

    # Determine the service name if bypass is disabled.
    if [ "$csi_bypass" = "FALSE" ]; then
        if [ -z "$2" ]; then
            case "$(dirname "$0")" in
                "/var/run/s6/etc/cont-init.d" | "/etc/cont-init.d" )
                    service=$(basename "$0")
                ;;
                *)
                    service=$(basename "$PWD")
                ;;
            esac
        else
            service=$2
        fi
    fi

    # Wait until the service initialization flag file is present.
    while [ ! -f /tmp/.container/"${service}${service_suffix}" ]; do
        print_debug "Waiting for service initialization: /tmp/.container/${service}${service_suffix}"
        sleep 1
    done

    # Clean up temporary variables.
    unset csi_bypass

    # Re-enable output after initialization is confirmed.
    output_on
}
