#!/command/with-contenv bash

# Source the main container functions
source /assets/functions/00-container

# Disable verbose output for cleaner logs
output_off

# Prepare single service startup
prepare_service

# Define process name for logging
PROCESS_NAME="logging"

# Check if log rotation is enabled in the container
if var_true "${CONTAINER_ENABLE_LOGROTATE}" ; then
    # Log a message indicating that log rotation is enabled
    print_debug "Enabling log rotation"

    # Determine the log compression method based on the configuration
    case "${LOGROTATE_COMPRESSION_TYPE,,}" in
        bz* )
            # Configure bzip2 compression for log rotation
            logrotate_compression=$(cat <<EOF
compress
compresscmd $(which bzip2)
compressext .bz2
compressoptions -${LOGROTATE_COMPRESSION_VALUE} ${LOGROTATE_COMPRESSION_EXTRA_PARAMETERS}
EOF
            )
        ;;
        gz* )
            # Configure gzip compression for log rotation
            logrotate_compression=$(cat <<EOF
compress
compresscmd $(which gzip)
compressext .gz
compressoptions -${LOGROTATE_COMPRESSION_VALUE} ${LOGROTATE_COMPRESSION_EXTRA_PARAMETERS}
EOF
            )
        ;;
        none )
            # Disable compression for log rotation
            logrotate_compression=""
        ;;
        zs* )
            # Configure zstd compression for log rotation
            logrotate_compression=$(cat <<EOF
compress
compresscmd $(which zstd)
compressext .zst
compressoptions -${LOGROTATE_COMPRESSION_VALUE} ${LOGROTATE_COMPRESSION_EXTRA_PARAMETERS}
EOF
            )
        ;;
    esac

    # Create the main logrotate configuration file
    cat <<EOF > /etc/logrotate.conf
daily
rotate ${LOGROTATE_RETAIN_DAYS}
copytruncate
dateext
nomail
notifempty
${logrotate_compression}
include /etc/logrotate.d
EOF

    # Set appropriate permissions for the logrotate configuration
    chmod 0744 /etc/logrotate.conf

    # Prepare the container's scheduling location for log rotation tasks
    mkdir -p "${CONTAINER_SCHEDULING_LOCATION}"

    # Add a cron job for daily log rotation
    cat <<EOF > "${CONTAINER_SCHEDULING_LOCATION}"/logrotate
# Scheduled log rotation job
# Generated on $(TZ=${TIMEZONE} date +'%Y-%m-%d %H:%M:%S %Z')

59 23 * * * logrotate -f /etc/logrotate.conf >/dev/null 2>&1
EOF
fi
