#!/command/with-contenv bash

# MONITORING CONFIGURATION SETTINGS
# ----------------------------------
# This script contains environment variables and logic for configuring
# the Zabbix agent, a monitoring tool used to track container performance.

# Zabbix log file settings
ZABBIX_AGENT_LOG_FILE=${ZABBIX_AGENT_LOG_FILE:-"zabbix_agentd.log"}
ZABBIX_AGENT_LOG_PATH=${ZABBIX_AGENT_LOG_PATH:-"/var/log/zabbix/agent/"}
ZABBIX_LOG_FILE_SIZE=${ZABBIX_LOG_FILE_SIZE:-"0"}

# Zabbix configuration file settings
ZABBIX_CONFIG_FILE=${ZABBIX_CONFIG_FILE:-"zabbix_agentd.conf"}
ZABBIX_CONFIG_PATH=${ZABBIX_CONFIG_PATH:-"/etc/zabbix/"}
ZABBIX_CERT_PATH=${ZABBIX_CERT_PATH:-"/etc/zabbix/certs/"}

# Zabbix hostname and networking
ZABBIX_HOSTNAME=${ZABBIX_HOSTNAME:-"${CONTAINER_NAME}"}
ZABBIX_LISTEN_IP=${ZABBIX_LISTEN_IP:-"0.0.0.0"}
ZABBIX_LISTEN_PORT=${ZABBIX_LISTEN_PORT:-"10050"}
ZABBIX_STATUS_PORT=${ZABBIX_STATUS_PORT:-"8050"}

# Zabbix buffer and performance
ZABBIX_BUFFER_SEND=${ZABBIX_BUFFER_SEND:-"5"}
ZABBIX_BUFFER_SIZE=${ZABBIX_BUFFER_SIZE:-"100"}
ZABBIX_MAXLINES_SECOND=${ZABBIX_MAXLINES_SECOND:-"20"}
ZABBIX_REFRESH_ACTIVE_CHECKS=${ZABBIX_REFRESH_ACTIVE_CHECKS:-"120"}

# Zabbix server and agent settings
ZABBIX_SERVER=${ZABBIX_SERVER:-"0.0.0.0/0"}
ZABBIX_SERVER_ACTIVE=${ZABBIX_SERVER_ACTIVE:-"zabbix-proxy"}
ZABBIX_START_AGENTS=${ZABBIX_START_AGENTS:-"1"}
ZABBIX_PID=${ZABBIX_PID:-"/var/lib/zabbix/run/zabbix-agent.pid"}
ZABBIX_SOCKET=${ZABBIX_SOCKET:-"/var/lib/zabbix/run/zabbix-agent.sock"}

# Zabbix debug and autoregistration
ZABBIX_DEBUGLEVEL=${ZABBIX_DEBUGLEVEL:-"1"}
ZABBIX_ENABLE_AUTOREGISTER=${ZABBIX_ENABLE_AUTOREGISTER:-"TRUE"}
ZABBIX_ENABLE_AUTOREGISTER_DNS=${ZABBIX_ENABLE_AUTOREGISTER_DNS:-"TRUE"}

# Zabbix user and permissions
ZABBIX_USER=${ZABBIX_USER:-"zabbix"}
ZABBIX_USER_SUDO=${ZABBIX_USER_SUDO:-"TRUE"}
ZABBIX_USER_DOAS=${ZABBIX_USER_DOAS:-"TRUE"}
ZABBIX_ALLOW_ROOT=${ZABBIX_ALLOW_ROOT:-"1"}

# Zabbix remote commands
ZABBIX_REMOTECOMMANDS_ALLOW=${ZABBIX_REMOTECOMMANDS_ALLOW:-"*"}
ZABBIX_REMOTECOMMANDS_LOG=${ZABBIX_REMOTECOMMANDS_LOG:-"1"}

# Zabbix agent setup
ZABBIX_SETUP_TYPE=${ZABBIX_SETUP_TYPE:-"AUTO"}

# Operating system detection and agent type setup
# -----------------------------------------------
# Detect the operating system and set the Zabbix agent type accordingly.
os=$(grep ^ID= /etc/os-release | cut -d= -f2)

case ${os} in
    "alpine" )
        osver=$(grep VERSION_ID /etc/os-release | cut -d= -f2 | cut -d. -f2 | cut -d_ -f1)
        if [ "${osver}" -ge 11 ] || [ "$osver" = "edge" ]; then
            ZABBIX_AGENT_TYPE=${ZABBIX_AGENT_TYPE:-"modern"}
        else
            ZABBIX_AGENT_TYPE=${ZABBIX_AGENT_TYPE:-"classic"}
        fi
    ;;
    "debian" | "ubuntu" )
        ZABBIX_AGENT_TYPE=${ZABBIX_AGENT_TYPE:-"modern"}
    ;;
esac
